---
version: "3.3"
services:
  traefik:
    image: traefik:2.11
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA_PATH}/traefik/letsencrypt:/letsencrypt
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - proxy
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sabnzbd:/config
      - ${DATA_ROOT_PATH}/data/usenet:/data/usenet
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for sabnzbd
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${DATA_ROOT_PATH}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for sonarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${DATA_ROOT_PATH}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for radarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for prowlarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/bazarr:/config
      - ${DATA_ROOT_PATH}/data/media/movies:/movies
      - ${DATA_ROOT_PATH}/data/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for bazarr
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${APPDATA_PATH}/jellyfin:/config
      - ${DATA_ROOT_PATH}/data/media:/data/media
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992" # Replace with the appropriate render group ID for your system
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`watch.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=le
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${APPDATA_PATH}/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`discover.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.tls.certresolver=le
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=* # Allow all hosts. Adjust as needed for security.
    volumes:
      - ${APPDATA_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for homepage
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/ddclient:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    networks:
      - proxy
    # No Traefik routing for ddclient

networks:
  proxy:
    name: proxy
    driver: bridge
