---
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin:8096
        description: Media Server
        container: jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: your_jellyfin_api_key
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://jellyseerr:5055
        description: Media Requests
        container: jellyseerr
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: your_jellyseerr_api_key

- Arr Suite:
    - Sonarr:
        icon: sonarr.png
        href: http://sonarr:8989
        description: TV Shows
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: your_sonarr_api_key
    - Radarr:
        icon: radarr.png
        href: http://radarr:7878
        description: Movies
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: your_radarr_api_key
    - Bazarr:
        icon: bazarr.png
        href: http://bazarr:6767
        description: Subtitles
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: your_bazarr_api_key
    - Prowlarr:
        icon: prowlarr.png
        href: http://prowlarr:9696
        description: Indexer Manager
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: your_prowlarr_api_key

- Downloads:
    - SABnzbd:
        icon: sabnzbd.png
        href: http://sabnzbd:8080
        description: Usenet Downloader
        container: sabnzbd
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: your_sabnzbd_api_key

- Infrastructure:
    - Traefik:
        icon: traefik.png
        href: http://traefik:8080
        description: Reverse Proxy
        container: traefik
        widget:
          type: traefik
          url: http://traefik:8080
